// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import finserv "gitlab.playcourt.id/new-mypertamina/myptm-gopayment-service/pkg/finserv"
import mock "github.com/stretchr/testify/mock"

// PaymentClient is an autogenerated mock type for the PaymentClient type
type PaymentClient struct {
	mock.Mock
}

// ConfirmForWebCheckout provides a mock function with given fields: ctx, pp
func (_m *PaymentClient) ConfirmForWebCheckout(ctx context.Context, pp *finserv.PaymentProperty) *finserv.ConfirmPaymentResult {
	ret := _m.Called(ctx, pp)

	var r0 *finserv.ConfirmPaymentResult
	if rf, ok := ret.Get(0).(func(context.Context, *finserv.PaymentProperty) *finserv.ConfirmPaymentResult); ok {
		r0 = rf(ctx, pp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finserv.ConfirmPaymentResult)
		}
	}

	return r0
}
